Create file of suggestions of posts and talks
androiddevbr/sugestoes-temas pull request #8
Opened 2018-07-10 00:34 UTC by orafaaraujo

The idea of this file is to maintain a repository of ideas for anyone who wants to create a post or a talk.

2018-07-10 13:49 UTC, davidtcdeveloper approved these changes
Não encontrei problemas, adicionei apenas sugestões.

2018-07-10 13:49 UTC, davidtcdeveloper commented on suggestion.MD
> +
Poderíamos ter um tópico sobre acessibilidade, o que acham?

2018-07-10 13:49 UTC, davidtcdeveloper commented on suggestion.MD
> +- A/B Testing
Poderíamos colocar esse tópico junto com outros tipo analítics em um grupo tipo "growth", o que acham?

2018-07-10 21:54 UTC, walmyrcarvalho requested changes
Em geral curti as sugestões de temas, só seria legal colocar em português, pra ficar de acordo com o resto do repo. Posso ajudar nas traduções, se quiserem! ;)

2018-07-10 21:54 UTC, walmyrcarvalho commented on suggestion.MD
> +
Acho excelente! :)

2018-07-10 21:54 UTC, walmyrcarvalho commented on suggestion.MD
> +- Material Design: Concepts and development
Acho que a gente pode traduzir tudo pra português também, assim fica de acordo com o resto do repo. O que acha?

2018-07-11 01:26 UTC, orafaaraujo commented on suggestion.MD
> +- Material Design: Concepts and development
Vou traduzir este e deixar outro em inglês, o que acha?

2018-07-11 02:46 UTC, orafaaraujo commented on suggestion.MD
> +- A/B Testing
Vou colocar apenas Growth hacking
Se tiver mais sugestões me diga

2018-08-20 11:49 UTC, merged